const cardActiionTypes = {
  ADD_NEW_ITEM: {
    START: 'CARD_ADD_NEW_ITEM_START',
    SUCCESS: 'CARD_ADD_NEW_ITEM_SUCCESS',
    FAIL: 'CARD_ADD_NEW_ITEM_FAIL',
  },
  FETCH_ITEMS: {
    START: 'CARD_FETCH_ITEMS_START',
    SUCCESS: 'CARD_FETCH_ITEMS_SUCCESS',
    FAIL: 'CARD_FETCH_ITEMS_FAIL',
  },
  UPDATE_ITEMS: {
    START: 'CARD_UPDATE_ITEMS_START',
    SUCCESS: 'CARD_UPDATE_ITEMS_SUCCESS',
    FAIL: 'CARD_UPDATE_ITEMS_FAIL',
  },
}

export default cardActiionTypes
