const sprintActiionTypes = {
  ADD_NEW_ITEM: {
    START: 'SPRINT_ADD_NEW_ITEM_START',
    SUCCESS: 'SPRINT_ADD_NEW_ITEM_SUCCESS',
    FAIL: 'SPRINT_ADD_NEW_ITEM_FAIL',
  },
  FETCH_ITEMS: {
    START: 'SPRINT_FETCH_ITEMS_START',
    SUCCESS: 'SPRINT_FETCH_ITEMS_SUCCESS',
    FAIL: 'SPRINT_FETCH_ITEMS_FAIL',
  },
  FETCH_ITEM_BY_ID: {
    START: 'SPRINT_FETCH_ITEM_BY_ID_START',
    SUCCESS: 'SPRINT_FETCH_ITEM_BY_ID_SUCCESS',
    FAIL: 'SPRINT_FETCH_ITEM_BY_ID_FAIL',
  },
}

export default sprintActiionTypes
